"""Aumentar tamanho do campo senha_hash

Revision ID: 87d3de2d727c
Revises: 
Create Date: 2024-10-21 17:24:05.940464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87d3de2d727c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               nullable=True)

    op.create_table('test_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
